name: Deploy Lambda Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:

  terraform:
    name: Terraform Verification and Push Lambda
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.0
          terraform_wrapper: false

      - name: Initialize Terraform for Lambda
        working-directory: deploy/terraform
        run: terraform init

      - name: Validate Terraform for Lambda
        working-directory: deploy/terraform
        run: terraform validate

      - name: Plan Terraform for Lambda
        if: github.ref == 'refs/heads/main'
        working-directory: deploy/terraform
        run: terraform plan -out=lambda

      - name: Apply Terraform for Lambda
        if: github.ref == 'refs/heads/main'
        working-directory: deploy/terraform
        run: terraform apply -auto-approve lambda